import type { Language } from "@/lib/language-context"

type PhraseMap = Record<Exclude<Language, "en">, Record<string, string>>

export const runtimePhraseMap: PhraseMap = {
  hi: {
    "Dashboard Overview": "डैशबोर्ड अवलोकन",
    "Smart Monitoring & Precision Agriculture Control Center": "स्मार्ट निगरानी और सटीक कृषि नियंत्रण केंद्र",
    "AI System Online": "एआई सिस्टम ऑनलाइन",
    "Active Detections": "सक्रिय पहचान",
    "Monitored Zones": "निगरानी वाले क्षेत्र",
    "Total Spraying": "कुल छिड़काव",
    "Avg. Soil Moisture": "औसत मिट्टी की नमी",
    "Needs Attention": "ध्यान देने की आवश्यकता",
    "Full Coverage": "पूर्ण कवरेज",
    "Season to date": "मौसम तक",
    "Live Telemetry": "लाइव टेलीमेट्री",
    "Interactive Farm Map": "इंटरैक्टिव फार्म मैप",
    "Click on zones to view detailed information and control spraying": "विस्तृत जानकारी और स्प्रे नियंत्रण के लिए क्षेत्रों पर क्लिक करें",
    "Reconfigure Farm": "फार्म पुनः कॉन्फ़िगर करें",
    "Safety Kill Switch": "सुरक्षा किल स्विच",
    "Live hardware lock, nozzle feedback, and sprayer path": "लाइव हार्डवेयर लॉक, नोजल फीडबैक और स्प्रेयर पथ",
    "Automation Ready": "ऑटोमेशन तैयार",
    "Smart Spray Control": "स्मार्ट स्प्रे नियंत्रण",
    "Manual zone override and automated distribution logic": "मैनुअल ज़ोन ओवरराइड और स्वचालित वितरण तर्क",
    "View All Activity": "सभी गतिविधि देखें",
    "Spray Now": "अभी स्प्रे करें",
    "Treatment Specs": "उपचार विनिर्देश",
    "Live data from detection engine": "डिटेक्शन इंजन से लाइव डेटा",
    "Sample Analysis": "नमूना विश्लेषण",
    "Select a high-resolution image of the affected leaf": "प्रभावित पत्ते की उच्च-रिज़ॉल्यूशन छवि चुनें",
    "Select Farm Zone": "फार्म ज़ोन चुनें",
    "Healthy Crop": "स्वस्थ फसल",
    "Detected on": "पर पाया गया",
    "AI Confidence": "एआई विश्वास",
    "Severity Level": "गंभीरता स्तर",
    "Target Zone": "लक्ष्य ज़ोन",
    "IPM Treatment Protocol": "आईपीएम उपचार प्रोटोकॉल",
    "Disease Insight": "रोग जानकारी",
    "Recommended Treatment": "अनुशंसित उपचार",
    "Alert: Action Required": "अलर्ट: कार्रवाई आवश्यक",
    "Monitoring Required": "निगरानी आवश्यक",
    "System Normal": "सिस्टम सामान्य",
    "Healthy": "स्वस्थ",
    "Warning": "चेतावनी",
    "Critical": "गंभीर",
    "Loading...": "लोड हो रहा है...",
    "View Farm Map": "फार्म मैप देखें",
    "Auto Spray": "ऑटो स्प्रे",
    "Disease Detection": "रोग पहचान",
    "Analytics": "विश्लेषण",
    "AI Recommendations": "एआई सिफारिशें",
    "Activity": "गतिविधि",
    "Users": "उपयोगकर्ता",
    "About": "परिचय",
    "Logout": "लॉगआउट"
  },
  mr: {
    "Dashboard Overview": "डॅशबोर्ड आढावा",
    "Smart Monitoring & Precision Agriculture Control Center": "स्मार्ट निरीक्षण आणि अचूक शेती नियंत्रण केंद्र",
    "AI System Online": "एआय सिस्टम ऑनलाइन",
    "Active Detections": "सक्रिय शोध",
    "Monitored Zones": "निरीक्षणातील झोन",
    "Total Spraying": "एकूण फवारणी",
    "Avg. Soil Moisture": "सरासरी माती आर्द्रता",
    "Needs Attention": "लक्ष देणे आवश्यक",
    "Full Coverage": "पूर्ण कव्हरेज",
    "Season to date": "हंगामापर्यंत",
    "Live Telemetry": "लाइव्ह टेलीमेट्री",
    "Interactive Farm Map": "परस्परसंवादी शेत नकाशा",
    "Reconfigure Farm": "शेत पुन्हा कॉन्फिगर करा",
    "Safety Kill Switch": "सुरक्षा किल स्विच",
    "Automation Ready": "ऑटोमेशन तयार",
    "Smart Spray Control": "स्मार्ट स्प्रे नियंत्रण",
    "View All Activity": "सर्व क्रियाकलाप पहा",
    "Spray Now": "आता फवारा",
    "Treatment Specs": "उपचार तपशील",
    "Sample Analysis": "नमुना विश्लेषण",
    "Select Farm Zone": "शेत झोन निवडा",
    "Healthy Crop": "निरोगी पिक",
    "AI Confidence": "एआय विश्वास",
    "Severity Level": "तीव्रता पातळी",
    "Target Zone": "लक्ष्य झोन",
    "Disease Insight": "रोग माहिती",
    "Recommended Treatment": "शिफारस केलेला उपचार",
    "Alert: Action Required": "इशारा: कृती आवश्यक",
    "Monitoring Required": "निगराणी आवश्यक",
    "System Normal": "प्रणाली सामान्य",
    "Healthy": "निरोगी",
    "Warning": "सावध",
    "Critical": "गंभीर",
    "Loading...": "लोड होत आहे...",
    "View Farm Map": "शेत नकाशा पहा",
    "Auto Spray": "ऑटो स्प्रे",
    "Disease Detection": "रोग शोध",
    "Analytics": "विश्लेषण",
    "AI Recommendations": "एआय शिफारसी",
    "Activity": "क्रियाकलाप",
    "Users": "वापरकर्ते",
    "About": "माहिती",
    "Logout": "लॉगआउट"
  },
  ta: {
    "Dashboard Overview": "டாஷ்போர்டு மேற்பார்வை",
    "Smart Monitoring & Precision Agriculture Control Center": "ஸ்மார்ட் கண்காணிப்பு மற்றும் துல்லிய வேளாண்மை கட்டுப்பாட்டு மையம்",
    "AI System Online": "ஏஐ அமைப்பு செயல்பாட்டில்",
    "Active Detections": "செயலில் உள்ள கண்டறிதல்கள்",
    "Monitored Zones": "கண்காணிக்கப்படும் மண்டலங்கள்",
    "Total Spraying": "மொத்த தெளிப்பு",
    "Avg. Soil Moisture": "சராசரி மண் ஈரப்பதம்",
    "Needs Attention": "கவனம் தேவை",
    "Full Coverage": "முழு கவரேஜ்",
    "Season to date": "இப்பருவம் வரை",
    "Live Telemetry": "நேரடி டெலிமெட்ரி",
    "Interactive Farm Map": "இணையச் செயற்பாட்டு பண்ணை வரைபடம்",
    "Reconfigure Farm": "பண்ணையை மறுகட்டமை",
    "Safety Kill Switch": "பாதுகாப்பு கில் சுவிட்ச்",
    "Automation Ready": "தானியக்கம் தயாராக உள்ளது",
    "Smart Spray Control": "ஸ்மார்ட் தெளிப்பு கட்டுப்பாடு",
    "View All Activity": "அனைத்து செயல்பாடுகளையும் காண்க",
    "Spray Now": "இப்போது தெளிக்கவும்",
    "Treatment Specs": "சிகிச்சை விவரங்கள்",
    "Sample Analysis": "மாதிரி பகுப்பாய்வு",
    "Select Farm Zone": "பண்ணை மண்டலத்தைத் தேர்வு செய்க",
    "Healthy Crop": "ஆரோக்கியமான பயிர்",
    "AI Confidence": "ஏஐ நம்பிக்கை",
    "Severity Level": "தீவிரம் நிலை",
    "Target Zone": "இலக்கு மண்டலம்",
    "Disease Insight": "நோய் விளக்கம்",
    "Recommended Treatment": "பரிந்துரைக்கப்பட்ட சிகிச்சை",
    "Alert: Action Required": "எச்சரிக்கை: நடவடிக்கை அவசியம்",
    "Monitoring Required": "கண்காணிப்பு தேவை",
    "System Normal": "அமைப்பு சாதாரணம்",
    "Healthy": "ஆரோக்கியம்",
    "Warning": "எச்சரிக்கை",
    "Critical": "மிகவும் மோசம்",
    "Loading...": "ஏற்றப்படுகிறது...",
    "View Farm Map": "பண்ணை வரைபடம் காண்க",
    "Auto Spray": "ஆட்டோ தெளிப்பு",
    "Disease Detection": "நோய் கண்டறிதல்",
    "Analytics": "பகுப்பாய்வு",
    "AI Recommendations": "ஏஐ பரிந்துரைகள்",
    "Activity": "செயல்பாடு",
    "Users": "பயனர்கள்",
    "About": "பற்றி",
    "Logout": "வெளியேறு"
  },
  te: {
    "Dashboard Overview": "డ్యాష్‌బోర్డ్ అవలోకనం",
    "Smart Monitoring & Precision Agriculture Control Center": "స్మార్ట్ మానిటరింగ్ మరియు ఖచ్చిత వ్యవసాయ నియంత్రణ కేంద్రం",
    "AI System Online": "ఏఐ సిస్టమ్ ఆన్‌లైన్‌లో ఉంది",
    "Active Detections": "క్రియాశీల గుర్తింపులు",
    "Monitored Zones": "పర్యవేక్షిత జోన్లు",
    "Total Spraying": "మొత్తం స్ప్రేయింగ్",
    "Avg. Soil Moisture": "సగటు నేల తేమ",
    "Needs Attention": "శ్రద్ధ అవసరం",
    "Full Coverage": "పూర్తి కవరేజ్",
    "Season to date": "ఈ సీజన్ వరకు",
    "Live Telemetry": "లైవ్ టెలీమెట్రీ",
    "Interactive Farm Map": "ఇంటరాక్టివ్ ఫార్మ్ మ్యాప్",
    "Reconfigure Farm": "ఫార్మ్‌ను మళ్లీ కాన్ఫిగర్ చేయండి",
    "Safety Kill Switch": "భద్రతా కిల్ స్విచ్",
    "Kill Switch": "తక్షణ ఆపు స్విచ్",
    "Safety Kill Switch is ON": "తక్షణ ఆపు స్విచ్ ఆన్‌లో ఉంది.",
    "Hardware commands are locked until you switch it off.": "మీరు ఆఫ్ చేసే వరకు హార్డ్‌వేర్ ఆదేశాలు లాక్‌లో ఉంటాయి.",
    "ENGAGED": "ఆన్‌లో ఉంది",
    "ENABLE": "ప్రారంభించు",
    "Automation Locked": "ఆటోమేషన్ లాక్‌లో ఉంది",
    "Automation Ready": "ఆటోమేషన్ సిద్ధంగా ఉంది",
    "Smart Spray Control": "స్మార్ట్ స్ప్రే నియంత్రణ",
    "Manual zone override and automated distribution logic": "మాన్యువల్ జోన్ నియంత్రణ మరియు స్వయంచాలక పంపిణీ విధానం",
    "View All Activity": "అన్ని కార్యకలాపాలు చూడండి",
    "Spray Now": "ఇప్పుడే స్ప్రే చేయండి",
    "Spraying...": "స్ప్రే జరుగుతోంది...",
    "Treatment Specs": "చికిత్స వివరాలు",
    "Live data from detection engine": "గుర్తింపు ఇంజిన్ నుండి ప్రత్యక్ష డేటా",
    "Farm Grid Map": "ఫార్మ్ గ్రిడ్ మ్యాప్",
    "Infected": "సంక్రమిత",
    "Pesticide": "పీడకనాశిని",
    "Category": "వర్గం",
    "Dosage": "మోతాదు",
    "Coverage": "కవరేజ్",
    "CALCULATION": "లెక్కింపు",
    "Selected Area": "ఎంచుకున్న విస్తీర్ణం",
    "Zone Count": "జోన్‌ల సంఖ్య",
    "Required Volume": "అవసరమైన పరిమాణం",
    "Analyze Leaf Pattern": "ఆకు నమూనా విశ్లేషించండి",
    "Neural Processing...": "న్యూరల్ ప్రాసెసింగ్ జరుగుతోంది...",
    "Sample Analysis": "నమూనా విశ్లేషణ",
    "Select a high-resolution image of the affected leaf": "ప్రభావిత ఆకుకు హై-రిజల్యూషన్ చిత్రాన్ని ఎంచుకోండి",
    "Select Farm Zone": "ఫార్మ్ జోన్ ఎంచుకోండి",
    "Healthy Crop": "ఆరోగ్యకర పంట",
    "Detected on": "పరిచయమైన పంట",
    "AI Confidence": "ఏఐ నమ్మకం",
    "Severity Level": "తీవ్రత స్థాయి",
    "Target Zone": "లక్ష్య జోన్",
    "System Activity Log": "వ్యవస్థ కార్యకలాపాల లాగ్",
    "Farm-wide Infection Probability": "ఫార్మ్ మొత్తంలో సంక్రమణ అవకాశ శాతం",
    "Risk Score": "ప్రమాద స్కోర్",
    "Highest Spread Risk Zones": "అత్యధిక వ్యాప్తి ప్రమాదం ఉన్న జోన్‌లు",
    "Disease Insight": "రోగ అవగాహన",
    "Recommended Treatment": "సిఫారసు చేసిన చికిత్స",
    "Alert: Action Required": "హెచ్చరిక: చర్య అవసరం",
    "Monitoring Required": "పర్యవేక్షణ అవసరం",
    "System Normal": "వ్యవస్థ సాధారణంగా ఉంది",
    "Healthy": "ఆరోగ్యకరం",
    "Warning": "హెచ్చరిక",
    "Critical": "తీవ్రం",
    "Loading...": "లోడ్ అవుతోంది...",
    "View Farm Map": "ఫార్మ్ మ్యాప్ చూడండి",
    "Auto Spray": "ఆటో స్ప్రే",
    "Disease Detection": "రోగ గుర్తింపు",
    "Analytics": "విశ్లేషణ",
    "AI Recommendations": "ఏఐ సిఫారసులు",
    "Activity": "కార్యకలాపం",
    "Users": "వినియోగదారులు",
    "About": "గురించి",
    "Logout": "లాగౌట్"
  },
}

export function getRuntimePhraseMap(language: Language): Record<string, string> {
  if (language === "en") return {}
  return runtimePhraseMap[language]
}
